import os
from dotenv import load_dotenv
import streamlit as st
import sqlite3
import google.generativeai as genai

load_dotenv()
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# Function to load gemini
def get_gemini_response(question, prompt):
    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content([prompt[0], question])
    return response.text.strip()  # Strip any leading/trailing whitespace

# Function to retrieve query from DB
def read_sql_query(sql, db):
    conn = sqlite3.connect(db)
    cur = conn.cursor()
    cur.execute(sql)
    rows = cur.fetchall()
    conn.close()  # Close connection after fetching data
    return rows

# Define your prompt
prompt = [
    """
    You are an expert in converting English questions to SQL query!
    The SQL database has the name STUDENT and has the following columns - NAME, CLASS, 
    SECTION \n\nFor example,\nExample 1 - How many entries of records are present?, 
    the SQL command will be something like this SELECT COUNT(*) FROM STUDENT ;
    \nExample 2 - Tell me all the students studying in Data Science class?, 
    the SQL command will be something like this SELECT * FROM STUDENT 
    where CLASS="Data Science"; 
    also the sql code should not have ``` in beginning or end and sql word in output
    """
]

# Streamlit App
st.set_page_config(page_title="I can retrieve any SQL Query")
st.header("Gemini App to retrieve SQL Data")
question = st.text_input("Input:", key="input")
submit = st.button("Ask the Question")
# If submit is clicked,
if submit:
    response = get_gemini_response(question, prompt)
    st.subheader("The Response is:")
    st.write(response)  # Display the SQL query generated by the model
    if response.lower().startswith("select"):  # Check if it's a select query
        data = read_sql_query(response, "student.db")
        if data:  # Check if data is retrieved
            st.write("Data retrieved from database:")
            for row in data:
                st.write(row)
        else:
            st.write("No data retrieved from database.")
